services:
  - type: web
    name: chatbot-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: TOGETHER_API_KEY
        value: 6efaf4cb8c42a59c4312fd61ba02a75a8f6064c9a9fc678aa2b5d3e39f2a08f6
